### ISSUE TITLE
RuntimeWarning Error During Execution of pymCADRE's 'rank_reactions'

### ISSUE THREAD

**Issue by Rohak72** [draeger-lab/pymCADRE#3]
Hi! I'm currently trying to apply pymCADRE to build a context-specific metabolic model. However, when I run the 'rank_reactions' method with my gene ID list (G), ubiquity scores (U), and reaction confidence scores specified, I'm met by a RuntimeWarning error that reads: 'All-NaN axis encountered'. Below is a screenshot of the full traceback:

<img width="800" alt="Screen Shot 2023-08-21 at 6 07 36 PM" src="https://github.com/draeger-lab/pymCADRE/assets/67394686/ca9850f4-2121-4f82-8e7d-70631124b44e">

What do you think could be going on here? If you would like me to send the model and inputs I'm using, I would be more than happy to do so. Any clarification/feedback would be greatly appreciated, thanks!

-Rohak

**Comment by NantiaL** [comment]
Hey @Rohak72, please excuse my late response. I would be happy to test your inputs if you would like to send them to me. Otherwise, I guess this error comes from the format of your input file.

**Comment by NantiaL** [comment]
Hey Rohak, 

Based on the format of your input data, and in the case of the variable U, your suggested Python code to read the file is correct.  Alternatively, you could use only
```
U = pd.read_csv('/Users/leonidou/Downloads/inputData.csv')
U = list(U['GeneCall'])
```
instead of 
```
U = U.rename(columns={0: "Scores"}) 
U = list(U['Scores'])
```

The rest does not need to be modified. 

Regarding the following points: 
(1) Your model uses Ensembl IDs but your inputData.csv includes EntrezIDs. If you have a way to map them and extract the associated ubiquity scores properly, then this method is fine. 
(2) Your classification criterion sounds logical. Alternatively, you could also set a threshold based on the distribution of values and consider everything above your cut-off to be 1 (expressed) and below to be 0 (not expressed). In case you have multiple samples, the ubiquity scores are calculated by taking the mean over all samples. It also depends on what the TreatmentExpr values are exactly.

I hope this answers your questions.

**Comment by NantiaL** [comment]
Hey Rohak, 

with your files I am getting the error: 

> TypeError: cannot pickle 'SwigPyObject' object

that is traced back to the COBRApy function `find_blocked_reactions()`. 

This seems to be due to the size of the model. Also using a model with over 10,000 reactions is definetely pretty challenging for conventional computer. 

Best regards
Nantia
